name: dan_starter
description: A sample command-line applicationto start a flutter app.
version: 1.0.0
repository: https://github.com/DReaper55/dan_starter.git

environment:
  sdk: ^3.3.1

dependencies:
  path: ^1.8.0
  args: ^2.3.0
  io: ^1.0.3
  process_run: ^0.12.0
  dcli: ^6.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

assets:
  - template/

executables:
  dan_starter: dan_starter